#ifndef CONSTANTS_H
#define CONSTANTS_H

#define WS_CLOCK_THRESHOLD 100
#define WS_CLOCK_PAGE_REPLACEMENT 0 
#define LEAST_RECENTLY_USED_PAGE_REPLACEMENT 1
#define SECOND_CHANCE_PAGE_REPLACEMENT 2


#endif